### ISSUE TITLE
data did not match any variant of untagged enum RequestUnion at line 1 column 1208

### ISSUE THREAD

**Issue by dmahesh19** [kevinswiber/postman2openapi#50]
While Using this Library to try to convert the postman collection to openapi file . Getting the following error

/Users/*******/node_modules/postman2openapi/postman2openapi.js:125
            throw takeObject(r1);
            ^
data did not match any variant of untagged enum RequestUnion at line 1 column 1208
Thrown at:
    at module.exports.transpile (/Users/********/node_modules/postman2openapi/postman2openapi.js:125:13)
    at /Users/***/PactBroker/pactbroker-app/tests_bidirectional/transform.js:18:17
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at executeUserEntryPoint (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

**Comment by kevinswiber** [comment]
Hey, @dmahesh19, thanks for reporting!  Do you have a collection I can use to reproduce the error?
